package com.devfahim00.duck.util

import android.content.Context
import android.net.Uri
import android.webkit.CookieManager
import java.io.File

/**
 * Cookie store backing yt-dlp's `--cookies` flag.
 *
 * Two ways to fill it (same idea as the Seal app):
 *
 *  1. **Built-in browser** (the easy way, Seal-style): open a site in
 *     Duck's embedded WebView, log in / pass the age gate, tap Done - all
 *     cookies the site set are exported automatically into the cookies file
 *     ([exportFromBrowser]). No browser extension, no file juggling.
 *
 *  2. **cookies.txt import** (the power-user way): export a Netscape
 *     cookies.txt from a desktop browser and pick the file here.
 *
 * The file lives in noBackupFilesDir (app-private, stable path). When the
 * built-in browser was used, the WebView's user-agent is remembered too and
 * sent along with the cookies (Seal does the same), because many sites bind
 * login sessions to the browser's user-agent string.
 */
object CookieStore {

    private const val COOKIES_NAME = "cookies.txt"
    private const val STAGING_NAME = "cookies.txt.new"

    /** Keys inside the app-wide "duck_settings" prefs. */
    private const val PREFS_NAME = "duck_settings"
    private const val PREF_UA = "cookies_user_agent"

    /** Netscape cookies.txt header, same as yt-dlp expects. */
    private val NETSCAPE_HEADER = listOf(
        "# Netscape HTTP Cookie File",
        "# https://curl.se/docs/http-cookies.html",
        "# Generated by Duck - do not edit.",
        ""
    )

    /** Simple stats for the Settings UI. */
    data class Stats(val cookies: Int, val sites: Int)

    fun file(context: Context): File =
        File(context.applicationContext.noBackupFilesDir, COOKIES_NAME)

    fun exists(context: Context): Boolean =
        file(context).let { it.exists() && it.length() > 0 }

    fun stats(context: Context): Stats? {
        val f = file(context)
        if (!f.exists() || f.length() == 0L) return null
        return runCatching { parseCookieLines(f.readText()) }
            .getOrNull()
            ?.takeIf { it.isNotEmpty() }
            ?.let { Stats(it.size, it.map { line -> line.domain }.distinct().size) }
    }

    /** The user-agent captured from the built-in browser, if any. */
    fun userAgent(context: Context): String? =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            .getString(PREF_UA, null)

    // ------------------------------------------------------------- browser flow

    /**
     * Harvests cookies for [hosts] from the WebView's global CookieManager,
     * merges them into the cookies file (new values replace old ones for the
     * visited domains; other domains are kept) and remembers [userAgent] for
     * later requests.
     *
     * Called when the user closes the built-in cookie browser. Returns the
     * number of cookies imported, or null when nothing could be harvested.
     */
    fun exportFromBrowser(context: Context, hosts: Set<String>, userAgent: String?): Int? {
        val appContext = context.applicationContext
        if (hosts.isEmpty()) return null

        val cookieManager = CookieManager.getInstance()
        runCatching { cookieManager.flush() }

        val expiry = System.currentTimeMillis() / 1000L + 365L * 24L * 3600L
        val fresh = mutableListOf<CookieLine>()
        val harvestedDomains = mutableSetOf<String>()

        for (host in hosts) {
            val base = baseDomain(host) ?: continue
            val header = runCatching { cookieManager.getCookie("https://$host") }.getOrNull()
                ?: runCatching { cookieManager.getCookie("http://$host") }.getOrNull()
                ?: continue
            harvestedDomains += ".$base"
            for (pair in header.split(";")) {
                val idx = pair.indexOf('=')
                if (idx <= 0) continue
                val name = pair.substring(0, idx).trim()
                val value = pair.substring(idx + 1).trim()
                if (name.isEmpty() || value.isEmpty()) continue
                fresh += CookieLine(domain = ".$base", name = name, value = value, expiry = expiry)
            }
        }
        if (fresh.isEmpty()) return null

        val target = file(appContext)
        val existing = if (target.exists()) {
            runCatching { parseCookieLines(target.readText()) }.getOrDefault(emptyList())
        } else {
            emptyList()
        }

        // Current browser state wins: drop old cookies for freshly visited
        // domains, keep everything for other domains.
        val kept = existing.filter { line ->
            harvestedDomains.none { domain -> line.domain.equals(domain, ignoreCase = true) }
        }
        // Dedupe within the harvest (a site visited via two hosts overlaps).
        val uniqueFresh = fresh.associateBy { it.domain + "\u0000" + it.name }.values

        val body = (kept + uniqueFresh)
            .sortedWith(compareBy({ it.domain }, { it.name }))
            .joinToString("\n") { it.toNetscapeLine() }

        target.writeText((NETSCAPE_HEADER.joinToString("\n") + body + "\n"))

        if (!userAgent.isNullOrBlank()) {
            appContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE).edit()
                .putString(PREF_UA, userAgent)
                .apply()
        }
        return uniqueFresh.size + kept.size
    }

    // ------------------------------------------------------------- file import

    /**
     * Copies the user-picked cookies.txt into app-private storage.
     *
     * @return null on success, otherwise a human readable error to show in
     * the settings sheet.
     */
    fun import(context: Context, uri: Uri): String? {
        val appContext = context.applicationContext
        val target = file(appContext)
        val staging = File(appContext.noBackupFilesDir, STAGING_NAME)
        return try {
            val input = appContext.contentResolver.openInputStream(uri)
                ?: return "Could not open the selected file"
            input.use { src ->
                staging.outputStream().use { out -> src.copyTo(out) }
            }
            if (staging.length() == 0L) {
                staging.delete()
                return "The selected file is empty"
            }
            if (!looksLikeCookiesFile(staging)) {
                staging.delete()
                return "That does not look like a Netscape cookies.txt file - " +
                    "export cookies from your browser again (cookie-export extensions produce this format)"
            }
            if (target.exists()) target.delete()
            if (!staging.renameTo(target)) {
                staging.copyTo(target, overwrite = true)
                staging.delete()
            }
            null
        } catch (e: Exception) {
            runCatching { staging.delete() }
            "Import failed: ${e.message?.take(120) ?: "unknown error"}"
        }
    }

    fun clear(context: Context) {
        val appContext = context.applicationContext
        runCatching {
            file(appContext).delete()
            File(appContext.noBackupFilesDir, STAGING_NAME).delete()
        }
        runCatching {
            CookieManager.getInstance().removeAllCookies(null)
            CookieManager.getInstance().flush()
        }
        appContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE).edit()
            .remove(PREF_UA)
            .apply()
    }

    // ----------------------------------------------------------------- helpers

    /** One parsed cookies.txt row. */
    private data class CookieLine(
        val domain: String,
        val path: String = "/",
        val secure: Boolean = true,
        val expiry: Long = 0L,
        val name: String,
        val value: String
    )

    private fun CookieLine.toNetscapeLine(): String =
        listOf(domain, "TRUE", path, if (secure) "TRUE" else "FALSE", "$expiry", name, value)
            .joinToString("\t")

    private fun parseCookieLines(text: String): List<CookieLine> =
        text.lines()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .mapNotNull { line ->
                val parts = line.split("\t")
                if (parts.size < 7) return@mapNotNull null
                CookieLine(
                    domain = parts[0].trim(),
                    path = parts[2].ifBlank { "/" },
                    secure = parts[3].equals("TRUE", ignoreCase = true),
                    expiry = parts[4].toLongOrNull() ?: 0L,
                    name = parts[5],
                    value = parts[6]
                )
            }

    /** "www.xnxx.com" / "m.example.com" -> "xnxx.com" / "example.com". */
    private fun baseDomain(host: String): String? {
        var h = host.trim().lowercase().removePrefix(".")
        while (true) {
            val cut = h.indexOf('.')
            if (cut <= 0 || cut == h.length - 1) break
            val label = h.substring(0, cut)
            if (label == "www" || label == "m" || label == "mobile") {
                h = h.substring(cut + 1)
            } else {
                break
            }
        }
        return h.takeIf { it.contains(".") }
    }

    /**
     * Light sanity check on the first lines of the file: Netscape cookies.txt
     * contains comment lines starting with '#' and/or tab-separated cookie
     * rows (domain, includeSubdomains, path, secure, expiry, name, value).
     * This catches accidentally picking a JSON/HTML file, which would fail
     * silently inside yt-dlp much later and confuse the user.
     */
    private fun looksLikeCookiesFile(f: File): Boolean = try {
        val head = mutableListOf<String>()
        f.inputStream().bufferedReader().use { reader ->
            var line = reader.readLine()
            while (line != null && head.size < 50) {
                head.add(line)
                line = reader.readLine()
            }
        }
        head.any { line ->
            line.startsWith("#") || line.split("\t").size >= 6
        }
    } catch (e: Exception) {
        // Unreadable head: let yt-dlp decide later instead of blocking the import.
        true
    }
}
